volumes:
  # docker volume create data-vol
  data-vol:

networks:
  # docker network create mynet
  mynet:

services:
  # docker run -d --name=mydb --netowrk=mynet --mount type=volume,src=data-vol,dst=/var/lib/mysql jaychenyj97/mydb:v1
  mydb:
    image: jaychenyj97/mydb:v1
    build: 
      context: database
    volumes:
      - data-vol:/var/lib/mysql
    networks:
      - mynet
  
  # docker run -d -p 8000-9000:3000 --network=mynet -d DB_HOST=mydb -e DB_USER=root -e DB_PASSWORD=changeit jaychenyj/myapp:v1
  myapp:
    image: jaychenyj97/myapp:v1
    build: 
      context: server
    environment:
      - DB_HOST=mydb
      - DB_USER=root
      - DB_PASSWORD=changeit
    networks:
      - mynet
    ports:
      - 8000-9000:3000
    depends_on:
      - mydb