---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deploy
  namespace: bggns
  labels:
    app: db-deploy
    name: db-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mydb
      commit: db001
  template:
    metadata: 
      name: mydbpod
      namespace: bggns
      labels:
        app: mydb
        commit: db001
    spec:
      containers:
      - name: mydbpo-container
        image:  stackupiss/bgg-database:v1
        imagePullPolicy: IfNotPresent
        ports:
        - name: db-port
          containerPort: 3306

# svc create name in DNS
# <service name>.<namespace>.svc.cluster.local
# example : dov-svc.myns.svc.cluster.local:8080
---
apiVersion: v1
kind: Service
metadata:
  name: bggdb-svc
  namespace: bggns
  labels:
    app: bggdb
    name: bggdb-svc
spec:
  type: ClusterIP
  selector: 
    app: mydb
    commit: db001
  ports:
  - port: 3306           # service port
    targetPort: db-port  # container port