---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bggdb-deploy
  namespace: bggns
  labels:
    app: bggdb
    name: bggdb-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bggdb
      dept: eng
      commit: abc123
  template:
    metadata:
      name: bggpod
      namespace: bggns
      labels:
        app: bggdb
        dept: eng
        commit: abc123
    spec:
      containers:
      - name: bggpod-container
        image: stackupiss/bgg-database:v1
        imagePullPolicy: IfNotPresent
        ports:
        - name: db-port
          containerPort: 3306

---
apiVersion: v1
kind: Service
metadata:
  name: bggdb-svc
  namespace: bggns
  labels:
    app: bggdb-deploy
    name: bggdb-svc
spec:
  type: ClusterIP
  selector:
    app: bggdb
    dept: eng
    commit: abc123
  ports:
  - port: 3306
    targetPort: db-port